- lib/index.js
In "sails-adapter-boilerplate" [index.js](https://github.com/balderdashy/sails-adapter-boilerplate/blob/master/index.js#L17-L18) it's suggested:
>  If you don't need / can't get to every method, just implement what you have time for.
That's great but the integration tests will probably break which is very annoying (and the sentiment is also shared by other users in balderdashy/sails-adapter-boilerplate#8 and #33).
This change adds support for mocha [chainable methods](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically#set-options) such as `invert()`. To use this, the adapter developer only needs to add a `mochaChainableMethods` object with keys matching the chainable methods and the values matching the arguments, example:
``` javascript
// Mocha options
// reference: …
```
> Adds support for mocha chainable methods 

- interfaces/associations/belongsTo/find.populate.js
The populate test falsely supposed an order that the records would be inserted and retrieved.  This removes that assumption, allowing sails-mysql tests to pass (fixes https://github.com/balderdashy/sails-mysql/issues/202).
> Remove order assumption from populate test.

- interfaces/semantic/find.test.js
- interfaces/sql/find.test.js
- interfaces/sql/query.test.js
- interfaces/sql/support/bootstrap.js
- interfaces/sql/support/fixtures/crud.fixture.js
- lib/index.js
As described in issue #40 (discussion and details there) create a new SQL interface to:
* Move SQL injection test to this interface;
* Enforce the existence of `.query()` method in adapters implementing this interface.
This fixes the breaking builds of sails-memory and sails-disk: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/56222494#L445 and also clears the broken test *Semantic Interface .find() should escape attribute names to prevent SQL injection attacks.* from sails-mongo and sails-redis builds.
Once this change is merged, this is how the overall test scenario will look like:
```
------------------------------------------------------------------- 
| adapter          | version | status  | failed | total | wl-sequel | …
```
> 40: Add Interface SQL

- interfaces/associations/belongsTo/create.js
- interfaces/associations/belongsTo/dynamicFinder.js
- interfaces/associations/belongsTo/find.populate.js
- interfaces/associations/belongsTo/findOne.populate.js
- interfaces/associations/belongsTo/update.nested.js
- interfaces/associations/find.associations.test.js
- interfaces/associations/hasMany/add.js
- interfaces/associations/hasMany/find.populate.js
- interfaces/associations/hasMany/find.populate.where.js
- interfaces/associations/hasMany/findOne.populate.js
- interfaces/associations/support/fixtures/hasMany.child.fixture.js
- interfaces/associations/support/fixtures/hasMany.parent.fixture.js
The assumption made by these tests that an association's attribute name and collection name are the same covered-up a bug in waterline (https://github.com/balderdashy/waterline/issues/533 / https://github.com/balderdashy/waterline/issues/930).  I think I've properly adjusted the model definitions for hasMany and belongsTo tests so that these bugs are exposed.  I'd love another set of eyes to go over this, though!
PR for proposed fix: https://github.com/balderdashy/waterline/issues/934
> Remove same-name association/collection assumption.

- interfaces/sql/query.test.js
- interfaces/sql/support/fixtures/crud.fixture.js
This should allow https://github.com/balderdashy/sails-postgresql/pull/145 to pass.  Cased table names are dealt with differently in different types of SQL DBs.
> Make sql interface query test less opinionated.

- interfaces/semantic/support/bootstrap.js
Force default `migrate: 'alter'` so it's independent from waterline core's default: balderdashy/waterline#887
Addresses balderdashy/waterline#887
> Force migrate 'alter' on tests

- interfaces/associations/hasMany/create.nested.js
- interfaces/associations/hasMany/update.nested.js
- interfaces/associations/manyToMany/find.populate.where.js
Similar to what @devinivy did in #43 and discussed in https://github.com/balderdashy/waterline/issues/887#issuecomment-95210555:
> the integration tests have 3 new broken sails-mysql tests:
> * Association Interface Has Many Association create nested associations() with single level depth and objects should create a new customer and payment association
> * Association Interface 1:m association :: .update() update nested associations() with single level depth when associations already exist should reset associations with the updated associations
> * Association Interface n:m association :: .find().populate([WHERE]) should return taxis using skip and limit
> 
> Build: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/59539534#L565
The above tests falsely supposed an order that …
> Remove order assumption from breaking MySQL tests

- .travis.yml
Following sails-mongo upgrade to use mongo 2.6.5 in balderdashy/sails-mongo#260 we need to update waterline-adapter-tests' .travis.yml to reflect the same changes: https://github.com/balderdashy/sails-mongo/pull/260/files#diff-354f30a63fb0907d4ad57269548329e3R5
And another adapter passes all integration tests :smiley: :
```
| sails-mongo      | 35fcc29 | success |      0 |   209 |           |
```
https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/60410937#L1792
> Update travis.yml to use mongo 2.6.5

- interfaces/associations/manyToMany/update.nested.js
- interfaces/queryable/modifiers/lessThan.modifier.test.js
The following tests have occasionally broke in automated builds:
* Queryable Interface Modifiers lessThanOrEqual (<=) integers should return records with lessThanOrEqual key
* Association Interface n:m association :: .update() update nested associations() with single level depth when associations already exist should reset associations with the updated associations
Example: https://travis-ci.org/dmarcelino/waterline-adapter-tests/jobs/60511975#L568
Remove assumption that `.find` will return the results in the same order they were created via waterline.
Similar to #43 and #52.
> Fix a few sails-mysql false positives by explicitly applying `sort`

- interfaces/semantic/create.test.js
This PR continues what @kevinburke did in #27 and changes it to test more records (https://github.com/balderdashy/waterline-adapter-tests/commit/883b47efca7158f552de8c4eedc39ea44b25bc22): original test:
> There's a test that create followed by find() returns results from the database
in the correct order, but no test that the create() callback checks the correct
ordering of results.
> 
> I'm trying to track down the behavior observed in https://github.com/balderdashy/sails-postgresql/issues/128
cc: @devinivy
> Test that create() returns results in correct order: 2

- interfaces/queryable/modifiers/lessThan.modifier.test.js
- interfaces/queryable/modifiers/not.modifier.test.js
Following the footsteps of #43, #52 and #56 remove `sort('id asc')` and replace with another fields as there is no guarantee that `id` expresses the insertion order.
Fixes #22.
cc: @adityamukho, @devinivy
> #22: make tests less opinionated about `id` order

- interfaces/queryable/modifiers/in.modifier.test.js
Some databases fail if your IN clause is empty. This test checks that
those sorts of queries are well behaved.
This test currently fails on sails-mysql - hence why I wrote the test :-)
> Test IN Query Modifier with empty array input.

- interfaces/semantic/types/array.type.js
- interfaces/semantic/types/binary.type.js
- interfaces/semantic/types/boolean.type.js
- interfaces/semantic/types/date.type.js
- interfaces/semantic/types/float.type.js
- interfaces/semantic/types/integer.type.js
- interfaces/semantic/types/json.type.js
- interfaces/semantic/types/string.type.js
The tests of data types (semantic/types) use the values returned from a .create() call, .create() retrieved only auto incremented ids from the table so the values returned in callback will be the same values passed as parameters, that's why the test should insert, and then query the table to retrieve the persistent value.
> Data Types Testing Issue

- lib/index.js
- test/integration/runner.js
The number of interfaces each adapter is tested against is printed before the tests start. This PR also adds the number of features being tested.
In this project camelCase is the standard file naming convention. Since feature test file paths are derived from the feature names it makes sense to standardize feature names in camelCase as well. This means the `cross-adapter` feature should become `crossAdapter`. The solution proposed here is backwards compatible.
> Two minor suggestions regarding #64

- .travis.yml
Since the build will run quicker as it won't have to install MongoDB 2.6.5.
Surprisingly, applying the same change to sails-mongo's .travis.yml ([branch travis-mongo-2.4](https://github.com/balderdashy/sails-mongo/tree/travis-mongo-2.4)) breaks the build with error:
* Association Interface Has Many Association create nested associations() with single level depth and objects mixed with ids should create a new customer and payment association
https://travis-ci.org/balderdashy/sails-mongo/jobs/61697570#L198
It may be because sails-mongo needs unreleased changed from waterline/waterline-adapter-tests. Anyway, we probably should get to the bottom of that and apply both changes simultaneously so both sails-mongo and integration tests are tested against the same target.
> Travis: falling back to mongo 2.4

- test/integration/config/sails-redis.json
Given that sails-redis now passes the integration tests (balderdashy/sails-redis#67), let the build fail if the opposite happens.
> Integration: throw error if sails-redis fails

- interfaces/queryable/modifiers/select.modifier.test.js
As mentioned in https://github.com/balderdashy/waterline/issues/366#issuecomment-102396946 this PR adds tests for the SELECT modifier.
Unfortunately, as happened previously on PR #53 sails-mongo is blocking this from being merged as it breaks the tests: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/62718504#L545.
Remaining task:
> Adds tests for SELECT modifier

- interfaces/semantic/support/bootstrap.js
- interfaces/semantic/support/fixtures/validations.fixture.js
- interfaces/semantic/update.test.js
Related to balderdashy/waterline#1003.
Strictly speaking this test can be seen as being redundant since [waterline/test/unit/query/query.update.js#L48-L53](https://github.com/balderdashy/waterline/blob/4653f8a18016d2bcde9a70c90dd63a7c69381935/test/unit/query/query.update.js#L48-L53) covers this scenario. The key difference is that in this case real adapters are used.
cc: @devinivy, @kvindasAB
> test .update() when missing required fields

- .gitignore
- .gitmodules
- .puppet/README.md
- .puppet/hiera.yaml
- .puppet/manifests/waterline-adapter-tests.pp
- .puppet/upgrade-puppet-v3.sh
- README.md
- Vagrantfile
When proposing changes to the tests they need to be run against all the core adapters and thus all the databases have to be installed on the host. This is not always desirable. My proposal is to use a [Vagrant VM](https://www.vagrantup.com/) where the databases can be installed automatically in a sandboxed environment. 
See the updates in the main README.md for more details on how this will work.
At the moment all core adapter databases except PostgreSQL are installed correctly. File permission issues are giving me headaches with Postgres, but if you like the solution I'll keep struggling with it until I find a solution. Then it should be ready to merge.
> Vagrant configuration for testing database adapters on a VM.

- features/unique/README.md
- features/unique/core/unique.test.js
- features/unique/support/unique.fixture.js
- features/unique/unique.test.js
When updating multiple records based on a given *find criteria* there won't be an `id` specified in the object with the new values. This could make it tricky, when a model has attributes marked as `unique`, to establish whether an existing record with a duplicate value is actually the record being updated, which is not actually a violation.
The `sails-memory` adapter has such a bug, and this test was added to flag it. I will reference this PR from the one I submit with the fix for the bug on the `sails-memory` repo.
> Added a Semantic test for updates when unique attributes are present.

- interfaces/queryable/modifiers/select.modifier.test.js
Following balderdashy/waterline#1098, adds a test to confirm that a `select` with empty criteria returns records.
> #1098: adds select test for empty criteria

- features/autoIncrement/core/autoIncrement.test.js
- see #85, #86 
@particlebanana there are a couple additional issues that I resolved. Since lastIds is actually 10 elements, not 5, there was a possibility still that ids in position 4 or 5 were out of order.
> removed inconsistent sorting expectation

- features/compositeUnique/core/compositeUnique.test.js
- features/compositeUnique/support/fixture.js
Tests the ability for an adapter to define one or more composite unique constraints.
An example attribute definition is here: https://github.com/tjwebb/waterline-adapter-tests/blob/a7168909acc540d88e76de6471dd8393039673d4/features/compositeUnique/support/fixture.js#L11-L25
> added tests for "compositeUnique" feature

- features/compositePrimaryKey/core/compositePrimaryKey.test.js
- features/compositePrimaryKey/support/fixture.js
- features/compositeUnique/core/compositeUnique.test.js
- features/compositeUnique/support/fixture.js
Tests the ability for an adapter to define a composite primary key on a table.
Example usage here: https://github.com/tjwebb/waterline-adapter-tests/blob/feature-compositePrimaryKey/features/compositePrimaryKey/support/fixture.js#L12-L20
> added tests for "compositePrimaryKey" feature

- interfaces/semantic/types/binary.type.js
They are broken everywhere so let's skip them so other test pass/fail until we can do a deep dive into binary blobs from Waterline down.
It's not a cloneDeep issue it's a serialization issue. We don't currently create `Buffer` values when a blob is used when we return the data.
> skip binary tests until they can be fixed

- features/crossAdapter/support/fixtures/manyToMany.taxi.fixture.js
- interfaces/associations/belongsTo/projections.js
- interfaces/associations/hasMany/projections.js
- interfaces/associations/hasManyThrough/projections.js
- interfaces/associations/manyToMany/projections.js
- interfaces/associations/support/fixtures/manyToMany.driver.fixture.js
- interfaces/associations/support/fixtures/manyToMany.taxi.fixture.js
- interfaces/queryable/projections.test.js
This is the start of adding tests to fully support projections across all adapters. It works in parallel to the main [PR](https://github.com/balderdashy/waterline/pull/1310) on Waterline.
> Tests for Waterline Projections
